# image will be published to ghcr.io/<user>/<name>
name: ublue-hyprland
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - hyprland
      - xdg-desktop-portal-hyprland
      - hyprcursor
      - waybar
      - papirus-icon-theme
      - swaybg
      - wofi
      - dunst
      - grim
      - slurp
      - wl-clipboard
      - brightnessctl
      - usbutils # lsusb
      - udisks2
      - udiskie
      - alacritty
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.vivaldi.Vivaldi
        - one.ablaze.floorp//lightning
        - com.github.tchx84.Flatseal
        - com.discordapp.Discord
        - com.valvesoftware.Steam
        - com.bitwarden.desktop
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

